services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spil
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: